service: bookmarks-table

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.8
  environment:
    BOOKMARKS_TABLE: ${self:service}
    SECRET_KEY: 'DE78B79CE52A0D55CDE52E825226A0A246DA71B4174EB6026964C0F33A1F7ADF'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.BOOKMARKS_TABLE}"

functions:
  fetch:
    handler: fetch.fetch
    package: {}
    events:
      - http:
          path: fetch
          method: get
          cors: true
  create:
    handler: create.create
    package: {}
    events:
      - http:
          path: create
          method: post
          cors: true
  delete:
    handler: delete.delete
    package: {}
    events:
      - http:
          path: delete/{nodeid}
          method: delete
          cors: true
  update:
    handler: update.update
    package: {}
    events:
      - http:
          path: update
          method: put
          cors: true

resources:
  Resources:
    BookmarksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userid
            AttributeType: S
        KeySchema:
          -
            AttributeName: userid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.BOOKMARKS_TABLE}

plugins:
  - serverless-python-requirements
